export const products = [
  // Electronics
  {
    name: "iPhone 16 Pro",
    slug: "iphone-16-pro",
    sku: "APL-IP16P",
    description: "Apple flagship smartphone with A18 Pro chip.",
    price: 129999,
    stock: 30,
    category: "electronics",
    brand: "apple",
    images: [
      "https://placehold.co/600x600?text=iPhone+16+Pro+1",
      "https://placehold.co/600x600?text=iPhone+16+Pro+2",
    ],
  },
  {
    name: "MacBook Air M4",
    slug: "macbook-air-m4",
    sku: "APL-MBA-M4",
    description: "Thin and lightweight laptop powered by Apple M4.",
    price: 149999,
    stock: 18,
    category: "electronics",
    brand: "apple",
    images: [
      "https://placehold.co/600x600?text=MacBook+Air+M4+1",
      "https://placehold.co/600x600?text=MacBook+Air+M4+2",
    ],
  },
  {
    name: "Apple Watch Series 10",
    slug: "apple-watch-series-10",
    sku: "APL-AW10",
    description: "Advanced smartwatch with health tracking.",
    price: 49999,
    stock: 25,
    category: "electronics",
    brand: "apple",
    images: [
      "https://placehold.co/600x600?text=Apple+Watch+1",
      "https://placehold.co/600x600?text=Apple+Watch+2",
    ],
  },
  {
    name: "Samsung Galaxy S25 Ultra",
    slug: "galaxy-s25-ultra",
    sku: "SMS-S25U",
    description: "Premium Android flagship smartphone.",
    price: 124999,
    stock: 28,
    category: "electronics",
    brand: "samsung",
    images: [
      "https://placehold.co/600x600?text=S25+Ultra+1",
      "https://placehold.co/600x600?text=S25+Ultra+2",
    ],
  },
  {
    name: "Samsung Galaxy Book 5",
    slug: "galaxy-book-5",
    sku: "SMS-GB5",
    description: "Windows ultrabook with AMOLED display.",
    price: 99999,
    stock: 15,
    category: "electronics",
    brand: "samsung",
    images: [
      "https://placehold.co/600x600?text=Galaxy+Book+1",
      "https://placehold.co/600x600?text=Galaxy+Book+2",
    ],
  },
  {
    name: "Sony WH-1000XM6",
    slug: "sony-wh1000xm6",
    sku: "SNY-XM6",
    description: "Industry-leading noise cancelling headphones.",
    price: 39999,
    stock: 40,
    category: "electronics",
    brand: "sony",
    images: [
      "https://placehold.co/600x600?text=XM6+1",
      "https://placehold.co/600x600?text=XM6+2",
    ],
  },
  {
    name: "Sony PlayStation 5",
    slug: "playstation-5",
    sku: "SNY-PS5",
    description: "Next generation gaming console.",
    price: 54999,
    stock: 20,
    category: "electronics",
    brand: "sony",
    images: [
      "https://placehold.co/600x600?text=PS5+1",
      "https://placehold.co/600x600?text=PS5+2",
    ],
  },
  {
    name: "Logitech MX Master 3S",
    slug: "mx-master-3s",
    sku: "LOG-MX3S",
    description: "Premium wireless productivity mouse.",
    price: 9999,
    stock: 60,
    category: "electronics",
    brand: "logitech",
    images: [
      "https://placehold.co/600x600?text=MX+Master+1",
      "https://placehold.co/600x600?text=MX+Master+2",
    ],
  },

  // Fashion
  {
    name: "Nike Air Max 270",
    slug: "nike-air-max-270",
    sku: "NK-AM270",
    description: "Comfortable everyday sneakers.",
    price: 12999,
    stock: 50,
    category: "fashion",
    brand: "nike",
    images: [
      "https://placehold.co/600x600?text=Air+Max+1",
      "https://placehold.co/600x600?text=Air+Max+2",
    ],
  },
  {
    name: "Nike Sports Hoodie",
    slug: "nike-sports-hoodie",
    sku: "NK-HOOD",
    description: "Soft fleece hoodie for daily wear.",
    price: 3999,
    stock: 70,
    category: "fashion",
    brand: "nike",
    images: [
      "https://placehold.co/600x600?text=Nike+Hoodie+1",
      "https://placehold.co/600x600?text=Nike+Hoodie+2",
    ],
  },
  {
    name: "Adidas Ultraboost 5",
    slug: "adidas-ultraboost-5",
    sku: "ADD-UB5",
    description: "High-performance running shoes.",
    price: 14999,
    stock: 40,
    category: "fashion",
    brand: "adidas",
    images: [
      "https://placehold.co/600x600?text=Ultraboost+1",
      "https://placehold.co/600x600?text=Ultraboost+2",
    ],
  },
  {
    name: "Adidas Track Jacket",
    slug: "adidas-track-jacket",
    sku: "ADD-TJ",
    description: "Classic sports jacket.",
    price: 4999,
    stock: 42,
    category: "fashion",
    brand: "adidas",
    images: [
      "https://placehold.co/600x600?text=Track+Jacket+1",
      "https://placehold.co/600x600?text=Track+Jacket+2",
    ],
  },
  {
    name: "Puma Velocity Nitro",
    slug: "puma-velocity-nitro",
    sku: "PMA-VN",
    description: "Running shoes built for speed.",
    price: 10999,
    stock: 35,
    category: "fashion",
    brand: "puma",
    images: [
      "https://placehold.co/600x600?text=Velocity+1",
      "https://placehold.co/600x600?text=Velocity+2",
    ],
  },
  {
    name: "Puma Training T-Shirt",
    slug: "puma-training-tshirt",
    sku: "PMA-TS",
    description: "Breathable workout t-shirt.",
    price: 1999,
    stock: 90,
    category: "fashion",
    brand: "puma",
    images: [
      "https://placehold.co/600x600?text=Puma+Tshirt+1",
      "https://placehold.co/600x600?text=Puma+Tshirt+2",
    ],
  },

  // Home
  {
    name: "IKEA Office Desk",
    slug: "ikea-office-desk",
    sku: "IK-DESK",
    description: "Modern wooden office desk.",
    price: 15999,
    stock: 20,
    category: "home-kitchen",
    brand: "ikea",
    images: [
      "https://placehold.co/600x600?text=Desk+1",
      "https://placehold.co/600x600?text=Desk+2",
    ],
  },
  {
    name: "IKEA Ergonomic Chair",
    slug: "ikea-ergonomic-chair",
    sku: "IK-CHAIR",
    description: "Comfortable chair for long work sessions.",
    price: 12999,
    stock: 25,
    category: "home-kitchen",
    brand: "ikea",
    images: [
      "https://placehold.co/600x600?text=Chair+1",
      "https://placehold.co/600x600?text=Chair+2",
    ],
  },
    // Home & Kitchen
  {
    name: "IKEA Coffee Table",
    slug: "ikea-coffee-table",
    sku: "IK-TABLE",
    description: "Minimalist wooden coffee table.",
    price: 8999,
    stock: 18,
    category: "home-kitchen",
    brand: "ikea",
    images: [
      "https://placehold.co/600x600?text=Coffee+Table+1",
      "https://placehold.co/600x600?text=Coffee+Table+2",
    ],
  },
  {
    name: "IKEA Bedside Lamp",
    slug: "ikea-bedside-lamp",
    sku: "IK-LAMP",
    description: "LED bedside lamp with adjustable brightness.",
    price: 2499,
    stock: 60,
    category: "home-kitchen",
    brand: "ikea",
    images: [
      "https://placehold.co/600x600?text=Lamp+1",
      "https://placehold.co/600x600?text=Lamp+2",
    ],
  },
  {
    name: "IKEA Bookshelf",
    slug: "ikea-bookshelf",
    sku: "IK-SHELF",
    description: "Five-tier wooden bookshelf.",
    price: 10999,
    stock: 22,
    category: "home-kitchen",
    brand: "ikea",
    images: [
      "https://placehold.co/600x600?text=Bookshelf+1",
      "https://placehold.co/600x600?text=Bookshelf+2",
    ],
  },
  {
    name: "IKEA Dining Table",
    slug: "ikea-dining-table",
    sku: "IK-DINE",
    description: "Modern dining table for six people.",
    price: 19999,
    stock: 12,
    category: "home-kitchen",
    brand: "ikea",
    images: [
      "https://placehold.co/600x600?text=Dining+Table+1",
      "https://placehold.co/600x600?text=Dining+Table+2",
    ],
  },

  // Books
  {
    name: "Clean Code",
    slug: "clean-code",
    sku: "BK-CC",
    description: "A Handbook of Agile Software Craftsmanship.",
    price: 799,
    stock: 100,
    category: "books",
    brand: "logitech",
    images: [
      "https://placehold.co/600x600?text=Clean+Code+1",
      "https://placehold.co/600x600?text=Clean+Code+2",
    ],
  },
  {
    name: "The Pragmatic Programmer",
    slug: "the-pragmatic-programmer",
    sku: "BK-PP",
    description: "Classic book for professional developers.",
    price: 899,
    stock: 80,
    category: "books",
    brand: "logitech",
    images: [
      "https://placehold.co/600x600?text=Pragmatic+1",
      "https://placehold.co/600x600?text=Pragmatic+2",
    ],
  },
  {
    name: "Atomic Habits",
    slug: "atomic-habits",
    sku: "BK-AH",
    description: "Build good habits and break bad ones.",
    price: 699,
    stock: 120,
    category: "books",
    brand: "logitech",
    images: [
      "https://placehold.co/600x600?text=Atomic+Habits+1",
      "https://placehold.co/600x600?text=Atomic+Habits+2",
    ],
  },
  {
    name: "Deep Work",
    slug: "deep-work",
    sku: "BK-DW",
    description: "Rules for focused success in a distracted world.",
    price: 649,
    stock: 70,
    category: "books",
    brand: "logitech",
    images: [
      "https://placehold.co/600x600?text=Deep+Work+1",
      "https://placehold.co/600x600?text=Deep+Work+2",
    ],
  },

  // Sports & Fitness
  {
    name: "Professional Football",
    slug: "professional-football",
    sku: "SP-FOOT",
    description: "FIFA-size professional football.",
    price: 1499,
    stock: 90,
    category: "sports-fitness",
    brand: "nike",
    images: [
      "https://placehold.co/600x600?text=Football+1",
      "https://placehold.co/600x600?text=Football+2",
    ],
  },
  {
    name: "Yoga Mat",
    slug: "yoga-mat",
    sku: "SP-YOGA",
    description: "Non-slip yoga mat for workouts.",
    price: 999,
    stock: 100,
    category: "sports-fitness",
    brand: "adidas",
    images: [
      "https://placehold.co/600x600?text=Yoga+Mat+1",
      "https://placehold.co/600x600?text=Yoga+Mat+2",
    ],
  },
  {
    name: "Adjustable Dumbbells",
    slug: "adjustable-dumbbells",
    sku: "SP-DUMB",
    description: "Adjustable dumbbells for strength training.",
    price: 6999,
    stock: 40,
    category: "sports-fitness",
    brand: "nike",
    images: [
      "https://placehold.co/600x600?text=Dumbbells+1",
      "https://placehold.co/600x600?text=Dumbbells+2",
    ],
  },
  {
    name: "Skipping Rope",
    slug: "skipping-rope",
    sku: "SP-ROPE",
    description: "Lightweight adjustable skipping rope.",
    price: 499,
    stock: 150,
    category: "sports-fitness",
    brand: "puma",
    images: [
      "https://placehold.co/600x600?text=Skipping+Rope+1",
      "https://placehold.co/600x600?text=Skipping+Rope+2",
    ],
  },
    // Beauty
  {
    name: "Daily Face Wash",
    slug: "daily-face-wash",
    sku: "BT-FW",
    description: "Gentle face wash suitable for all skin types.",
    price: 399,
    stock: 120,
    category: "beauty",
    brand: "sony",
    images: [
      "https://placehold.co/600x600?text=Face+Wash+1",
      "https://placehold.co/600x600?text=Face+Wash+2",
    ],
  },
  {
    name: "Vitamin C Serum",
    slug: "vitamin-c-serum",
    sku: "BT-VCS",
    description: "Brightening serum enriched with Vitamin C.",
    price: 899,
    stock: 80,
    category: "beauty",
    brand: "sony",
    images: [
      "https://placehold.co/600x600?text=Vitamin+C+1",
      "https://placehold.co/600x600?text=Vitamin+C+2",
    ],
  },
  {
    name: "Moisturizing Cream",
    slug: "moisturizing-cream",
    sku: "BT-MC",
    description: "Deep hydration for dry and sensitive skin.",
    price: 699,
    stock: 90,
    category: "beauty",
    brand: "sony",
    images: [
      "https://placehold.co/600x600?text=Moisturizer+1",
      "https://placehold.co/600x600?text=Moisturizer+2",
    ],
  },
  {
    name: "SPF 50 Sunscreen",
    slug: "spf-50-sunscreen",
    sku: "BT-SPF",
    description: "Broad-spectrum SPF 50 sunscreen.",
    price: 599,
    stock: 140,
    category: "beauty",
    brand: "sony",
    images: [
      "https://placehold.co/600x600?text=Sunscreen+1",
      "https://placehold.co/600x600?text=Sunscreen+2",
    ],
  },

  // Electronics
  {
    name: "Samsung Galaxy Buds 3 Pro",
    slug: "galaxy-buds-3-pro",
    sku: "SMS-BUDS3",
    description: "Premium wireless earbuds with ANC.",
    price: 16999,
    stock: 45,
    category: "electronics",
    brand: "samsung",
    images: [
      "https://placehold.co/600x600?text=Galaxy+Buds+1",
      "https://placehold.co/600x600?text=Galaxy+Buds+2",
    ],
  },
  {
    name: "Sony Bravia 55 4K TV",
    slug: "sony-bravia-55-4k-tv",
    sku: "SNY-TV55",
    description: "55-inch Ultra HD Smart TV.",
    price: 79999,
    stock: 10,
    category: "electronics",
    brand: "sony",
    images: [
      "https://placehold.co/600x600?text=Bravia+1",
      "https://placehold.co/600x600?text=Bravia+2",
    ],
  },
  {
    name: "Logitech G Pro X Keyboard",
    slug: "logitech-g-pro-x-keyboard",
    sku: "LOG-GPK",
    description: "Mechanical gaming keyboard.",
    price: 11999,
    stock: 35,
    category: "electronics",
    brand: "logitech",
    images: [
      "https://placehold.co/600x600?text=Keyboard+1",
      "https://placehold.co/600x600?text=Keyboard+2",
    ],
  },
  {
    name: "Logitech C920 Webcam",
    slug: "logitech-c920-webcam",
    sku: "LOG-C920",
    description: "Full HD webcam for streaming.",
    price: 6999,
    stock: 50,
    category: "electronics",
    brand: "logitech",
    images: [
      "https://placehold.co/600x600?text=Webcam+1",
      "https://placehold.co/600x600?text=Webcam+2",
    ],
  },

  // Fashion
  {
    name: "Nike Backpack",
    slug: "nike-backpack",
    sku: "NK-BAG",
    description: "Durable everyday backpack.",
    price: 2999,
    stock: 65,
    category: "fashion",
    brand: "nike",
    images: [
      "https://placehold.co/600x600?text=Backpack+1",
      "https://placehold.co/600x600?text=Backpack+2",
    ],
  },
  {
    name: "Adidas Cap",
    slug: "adidas-cap",
    sku: "ADD-CAP",
    description: "Classic sports cap.",
    price: 1499,
    stock: 80,
    category: "fashion",
    brand: "adidas",
    images: [
      "https://placehold.co/600x600?text=Cap+1",
      "https://placehold.co/600x600?text=Cap+2",
    ],
  },
  {
    name: "Puma Sweatpants",
    slug: "puma-sweatpants",
    sku: "PMA-SP",
    description: "Comfortable cotton sweatpants.",
    price: 2499,
    stock: 70,
    category: "fashion",
    brand: "puma",
    images: [
      "https://placehold.co/600x600?text=Sweatpants+1",
      "https://placehold.co/600x600?text=Sweatpants+2",
    ],
  },
  {
    name: "Nike Running Shorts",
    slug: "nike-running-shorts",
    sku: "NK-SHORTS",
    description: "Lightweight running shorts.",
    price: 1799,
    stock: 95,
    category: "fashion",
    brand: "nike",
    images: [
      "https://placehold.co/600x600?text=Shorts+1",
      "https://placehold.co/600x600?text=Shorts+2",
    ],
  },
];